---

- name: install php
  apt:
      name: software-properties-common
  become: yes
- name: add repository
  apit-repository:
      repo: ppa:ondrej/ph
      state: present
  become: yes
- name: apt update
  apt:
      update_cache: yes
  become: yes
- name: install php72
  apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
  vars:
      packages:
          - php7.2-fpm
          - php7.2-common
          - php7.2-mbstring
          - php7.2-xmlrpc
          - php7.2-soap
          - php7.2-gd
          - php7.2-xml
          - php7.2-intl
          - php7.2-mysql
          - php7.2-cli
          - php7.2-zip
          - php7.2-curl
