---

- name: install php
  apt:
      name: software-properties-common
      update_cache: yes
  become: yes
- name: add repository
  apt_repository:
      repo: ppa:ondrej/php
      state: present
  become: yes
- name: apt update
  apt:
      update_cache: yes
  become: yes
- name: install php72
  apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
  vars:
      packages:
          - php7.2-fpm
          - php7.2-common
          - php7.2-mbstring
          - php7.2-xmlrpc
          - php7.2-soap
          - php7.2-gd
          - php7.2-xml
          - php7.2-intl
          - php7.2-mysql
          - php7.2-cli
          - php7.2-zip
          - php7.2-curl
  become: yes
- name: configure php.ini
  lineinfile:
      path: /etc/php/7.2/fpm/php.ini
      regexp: '^memory_limit ='
      line: 'memory_limit = 256M'
  become: yes
- name: configure php.ini
  lineinfile:
      path: /etc/php/7.2/fpm/php.ini
      regexp: '^upload_max_filesize ='
      line: 'upload_max_filesize = 100M'
  become: yes
- name: configure php.ini
  lineinfile:
      path: /etc/php/7.2/fpm/php.ini
      regexp: '^;cgi.fix_pathinfo='
      line: 'cgi.fix_pathinfo=0'
  become: yes
- name: configure php.ini
  lineinfile:
      path: /etc/php/7.2/fpm/php.ini
      regexp: '^max_execution_time ='
      line: 'max_execution_time = 360'
  become: yes
- name: configure php.ini
  lineinfile:
      path: /etc/php/7.2/fpm/php.ini
      regexp: '^;date.timezone ='
      line: 'date.timezone = Netherlands/Amsterdam' 
  become: yes
- name: restart services
  systemd:
      name: "{{ item }}"
      daemon_reload: yes
      state: restarted
   loop:
       - nginx.service
       - php7.2-fpm.service

